## Q1(A): Minimum, Mean, Standard Deviation using Axis
Compute `min`, `mean`, `std` on a **1-D** and a **2-D** array.  
**Axis rule:** `axis=0` collapses **rows** (works column-wise); `axis=1` collapses **columns** (works row-wise).

In [1]:
import numpy as np

# ─── 1-D Array ────────────────────────────────────────────────────────────
# Think of this as a simple list of numbers
arr1d = np.array([4, 7, 2, 9, 1, 5])

print("1-D Array Analysis:")
print("Min value: ", np.min(arr1d))
print("Mean (Avg):", np.mean(arr1d))
print("Std Dev:   ", np.std(arr1d))

print("-" * 30)

# ─── 2-D Array (3 rows × 4 cols) ─────────────────────────────────────────
arr2d = np.array([[3, 7, 1, 8],
                  [5, 2, 9, 4],
                  [6, 0, 3, 7]])

print("2-D Array Matrix:")
print(arr2d)
print()

# --- STEP 1: MINIMUMS ---
# No rounding needed for whole numbers
overall_min = np.min(arr2d)
col_min     = np.min(arr2d, axis=0) # Smallest in each column
row_min     = np.min(arr2d, axis=1) # Smallest in each row

print("Smallest overall:", overall_min)
print("Smallest by col:", col_min)
print("Smallest by row:", row_min)
print()

# --- STEP 2: MEANS (AVERAGES) ---
# These may result in long decimals; we just print them as they are
overall_mean = np.mean(arr2d)
col_mean     = np.mean(arr2d, axis=0)
row_mean     = np.mean(arr2d, axis=1)

print("Average overall:", overall_mean)
print("Average by col:", col_mean)
print("Average by row:", row_mean)

1-D Array Analysis:
Min value:  1
Mean (Avg): 4.666666666666667
Std Dev:    2.748737083745107
------------------------------
2-D Array Matrix:
[[3 7 1 8]
 [5 2 9 4]
 [6 0 3 7]]

Smallest overall: 0
Smallest by col: [3 0 1 4]
Smallest by row: [1 2 0]

Average overall: 4.583333333333333
Average by col: [4.66666667 3.         4.33333333 6.33333333]
Average by row: [4.75 5.   4.  ]


---
## Q1(B): Main Attributes of a NumPy Array
Every `ndarray` object comes with these built-in properties.

In [2]:
import numpy as np
printf = print

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
printf('Array:')
printf(arr)
printf()
printf('ndim     :', arr.ndim)      # number of dimensions/axes (1=vector, 2=matrix)
printf('shape    :', arr.shape)     # (rows, columns) as a tuple
printf('size     :', arr.size)      # total elements = rows × cols
printf('dtype    :', arr.dtype)     # type stored in each cell (int64, float64, ...)

Array:
[[1 2 3]
 [4 5 6]]

ndim     : 2
shape    : (2, 3)
size     : 6
dtype    : int64


---
## Q1(C): Slicing of a 2-D NumPy Array
**Syntax:** `arr[row_start:row_stop, col_start:col_stop]`  
• Indices are **0-based** • Stop index is **excluded** • `:` alone means *all*

In [3]:
import numpy as np

arr = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12],
                [13, 14, 15, 16]])
print('Original 4×4 array:')
print(arr)
print()

print('Single element  arr[1, 2]  :', arr[1, 2])     # row 1, col 2  →  7
print('Entire row 2    arr[2, :]  :', arr[2, :])     # all cols of row 2
print('Entire col 3    arr[:, 3]  :', arr[:, 3])     # all rows of col 3
print('Sub-matrix  arr[0:2, 1:3]  :')                # rows 0-1, cols 1-2
print(arr[0:2, 1:3])
print('Last 2 rows, first 2 cols  :')                # negative index = from end
print(arr[-2:, :2])
print('Every alternate row (step=2):')
print(arr[::2, :])
print('Rows in reverse (step=-1)  :')
print(arr[::-1, :])

Original 4×4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Single element  arr[1, 2]  : 7
Entire row 2    arr[2, :]  : [ 9 10 11 12]
Entire col 3    arr[:, 3]  : [ 4  8 12 16]
Sub-matrix  arr[0:2, 1:3]  :
[[2 3]
 [6 7]]
Last 2 rows, first 2 cols  :
[[ 9 10]
 [13 14]]
Every alternate row (step=2):
[[ 1  2  3  4]
 [ 9 10 11 12]]
Rows in reverse (step=-1)  :
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


---
## Q1(D): AX = B - Unique / Infinite / No Solution (with Geometric Interpretation)
| Condition | Result | Geometry (2D) |

In [4]:
import numpy as np

# 1. Input the numbers for two lines:
# Line 1: ax + by = e
# Line 2: cx + dy = f
print("--- Equation 1 (ax + by = e) ---")
a = float(input("Enter a: "))
b = float(input("Enter b: "))
e = float(input("Enter e: "))

print("\n--- Equation 2 (cx + dy = f) ---")
c = float(input("Enter c: "))
d = float(input("Enter d: "))
f = float(input("Enter f: "))

# 2. Put them into a NumPy Array (Matrix A)
A = np.array([[a, b], 
              [c, d]])

# 3. Calculate the Determinant manually: (a*d - b*c)
# This tells us if the lines are parallel or if they cross.
det = (A[0,0] * A[1,1]) - (A[0,1] * A[1,0])

print(f"\nMatrix A:\n{A}")
print(f"Determinant: {det}")

# 4. Logic based on traditional Algebra:
if det != 0:
    print("Result: UNIQUE SOLUTION (The lines cross at one point)")
    
    # Optional: Solving for X and Y using Cramer's Rule (Basic Math)
    x = ((e * d) - (b * f)) / det
    y = ((a * f) - (e * c)) / det
    print(f"Solution: x = {x}, y = {y}")

else:
    # If determinant is 0, they are either the same line or parallel
    # We check if the "totals" (e and f) follow the same ratio
    if (a / c) == (e / f):
        print("Result: INFINITE SOLUTIONS (It's the same line)")
    else:
        print("Result: NO SOLUTION (The lines are parallel)")

--- Equation 1 (ax + by = e) ---


Enter a:  1
Enter b:  2
Enter e:  3



--- Equation 2 (cx + dy = f) ---


Enter c:  4
Enter d:  6
Enter f:  7



Matrix A:
[[1. 2.]
 [4. 6.]]
Determinant: -2.0
Result: UNIQUE SOLUTION (The lines cross at one point)
Solution: x = -2.0, y = 2.5


---
## Q1(E-a): Check if Matrix is Symmetric
A matrix is **symmetric** when `A == A.T` (it equals its own transpose).

In [5]:
import numpy as np
printf = print

sym = np.array([[1, 2, 3],
                [2, 5, 6],
                [3, 6, 9]])

not_sym = np.array([[1, 2],
                    [3, 4]])

# np.array_equal(A, B) checks element-by-element equality of two arrays
# .T is the transpose — rows and columns are swapped
printf('Matrix sym:')
printf(sym)
printf('Is symmetric?', np.array_equal(sym, sym.T))          # True
printf()
printf('Matrix not_sym:')
printf(not_sym)
printf('Is symmetric?', np.array_equal(not_sym, not_sym.T))  # False

Matrix sym:
[[1 2 3]
 [2 5 6]
 [3 6 9]]
Is symmetric? True

Matrix not_sym:
[[1 2]
 [3 4]]
Is symmetric? False


## Q1(E-b): Trace of a Matrix
**Trace = sum of all main diagonal elements** (top-left to bottom-right).

In [6]:
import numpy as np
printf = print

M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
printf('Matrix:')
printf(M)
printf()
printf('Diagonal elements (np.diag) :', np.diag(M))     # extracts [1, 5, 9]
printf('Trace using np.trace()      :', np.trace(M))    # 1 + 5 + 9 = 15

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal elements (np.diag) : [1 5 9]
Trace using np.trace()      : 15


## Q1(E-c): Upper Triangular / Lower Triangular / Diagonal Matrix?

In [7]:
import numpy as np
printf = print

def classify_matrix(M):
    # np.tril(M) → keeps only lower triangle (zeros everything ABOVE diagonal)
    # np.triu(M) → keeps only upper triangle (zeros everything BELOW diagonal)
    # If M equals its own tril → all above-diagonal elements are already 0 → Lower Triangular
    # If M equals its own triu → all below-diagonal elements are already 0 → Upper Triangular
    # If BOTH conditions hold  → all off-diagonal elements are 0 → Diagonal
    is_lower = np.array_equal(M, np.tril(M))
    is_upper = np.array_equal(M, np.triu(M))
    if is_lower and is_upper: return 'Diagonal Matrix'
    if is_upper:              return 'Upper Triangular Matrix'
    if is_lower:              return 'Lower Triangular Matrix'
    return 'Neither triangular nor diagonal'

upper = np.array([[1, 2, 3], [0, 4, 5], [0, 0, 6]])  # zeros below diagonal
lower = np.array([[1, 0, 0], [4, 5, 0], [7, 8, 9]])  # zeros above diagonal
diag  = np.array([[3, 0, 0], [0, 7, 0], [0, 0, 2]])  # zeros everywhere off-diagonal
other = np.array([[1, 2], [3, 4]])                    # general matrix

for name, mat in [('upper', upper), ('lower', lower), ('diag', diag), ('other', other)]:
    printf(f'{name:6s}  →  {classify_matrix(mat)}')

upper   →  Upper Triangular Matrix
lower   →  Lower Triangular Matrix
diag    →  Diagonal Matrix
other   →  Neither triangular nor diagonal


## Q1(E-d): Convert Matrix to 1-D - `flatten()` vs `ravel()`

In [8]:
import numpy as np
printf = print

M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
printf('Original matrix (3×3):')
printf(M)
printf()

# flatten() → always returns a brand-new COPY
# Modifying the flat array does NOT change the original
f = M.flatten()
printf('flatten():', f)
f[0] = 999
printf('After f[0]=999 → M[0,0] =', M[0, 0], '  ← UNCHANGED (flatten is a copy)')
printf()

# ravel() → returns a VIEW when memory layout allows
# Modifying the flat array DOES change the original
M2 = M.copy()   # fresh copy to demonstrate ravel
r = M2.ravel()
printf('ravel(): ', r)
r[0] = 999
printf('After r[0]=999 → M2[0,0] =', M2[0, 0], ' ← CHANGED (ravel is a view)')
printf()
printf('Rule: use flatten() for safety, ravel() for speed/memory efficiency.')

Original matrix (3×3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

flatten(): [1 2 3 4 5 6 7 8 9]
After f[0]=999 → M[0,0] = 1   ← UNCHANGED (flatten is a copy)

ravel():  [1 2 3 4 5 6 7 8 9]
After r[0]=999 → M2[0,0] = 999  ← CHANGED (ravel is a view)

Rule: use flatten() for safety, ravel() for speed/memory efficiency.


## Q1(E-e): Change Diagonal to 1 in 4×2 Matrix; Make Upper Triangular

In [9]:
import numpy as np
printf = print

# ─── Part 1: fill_diagonal on a 4×2 matrix ────────────────────────────────
# A 4×2 matrix has only 2 diagonal positions: (0,0) and (1,1)
M = np.array([[5, 8],
              [3, 7],
              [9, 2],
              [4, 6]])
printf('Original 4×2 matrix:')
printf(M)

np.fill_diagonal(M, 1)   # sets (0,0) and (1,1) to 1; rows 2,3 are untouched
printf('After np.fill_diagonal(M, 1):')
printf(M)
printf()

# ─── Part 2: Convert to Upper Triangular ──────────────────────────────────
# np.triu(M) zeroes out all elements BELOW the main diagonal
M2 = np.array([[4, 3, 2],
               [1, 5, 6],
               [7, 8, 9]])
printf('Original 3×3 matrix:')
printf(M2)
printf('np.triu(M2) → Upper Triangular:')
printf(np.triu(M2))

Original 4×2 matrix:
[[5 8]
 [3 7]
 [9 2]
 [4 6]]
After np.fill_diagonal(M, 1):
[[1 8]
 [3 1]
 [9 2]
 [4 6]]

Original 3×3 matrix:
[[4 3 2]
 [1 5 6]
 [7 8 9]]
np.triu(M2) → Upper Triangular:
[[4 3 2]
 [0 5 6]
 [0 0 9]]


## Q1(E-f): Is the User-Input Matrix Square?
A **square matrix** has equal number of rows and columns.

In [10]:
import numpy as np

# 1. Get dimensions and data in a more compact way
rows = int(input('Rows: '))
print('Enter each row (space-separated):')

# We can build the list directly inside the array constructor
M = np.array([input(f'Row {i+1}: ').split() for i in range(rows)], dtype=float)

# 2. Display Matrix Info
print(f'\nMatrix:\n{M}\nShape: {M.shape}')

# 3. Simplify the Square Check (using a conditional expression)
is_square = "SQUARE" if M.shape[0] == M.shape[1] else "NOT square"
print(f'Result: {is_square} ({M.shape[0]}x{M.shape[1]})')

# 4. Added: Calculate the Rank
rank = np.linalg.matrix_rank(M)
print(f'Rank of Matrix: {rank}')

Enter number of rows   :  3
Enter number of columns:  5


Enter each row (space-separated values):


  Row 1:  6
  Row 2:  8
  Row 3:  9



Your matrix:
[[6.]
 [8.]
 [9.]]
Shape: (3, 1)

Result: NOT a square matrix  (3 rows ≠ 1 columns)
